
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/myrh
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password770


  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=myrh
      - POSTGRES_PASSWORD=password770
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"